name: FFmpeg Base Image

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/FFmpeg.yml'
      - 'src/PodScrub.Api/Dockerfile-FFmpeg'

jobs:
  ffmpeg:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract .NET major version
        id: extract_version
        shell: pwsh
        run: |
          [xml]$xml = Get-Content 'Directory.Build.props'
          $tfm = $xml.Project.PropertyGroup.TargetFramework
          $majorVersion = [regex]::Match($tfm, '\d+').Value
          Write-Output "major_version=$majorVersion" >> $env:GITHUB_OUTPUT

      - name: Build and push Docker image for FFmpeg
        uses: docker/build-push-action@v7
        with:
          push: true
          provenance: false
          platforms: linux/arm64,linux/amd64
          tags: |
            ghcr.io/mu88/podscrub-ffmpeg:latest
            ghcr.io/mu88/podscrub-ffmpeg:${{ steps.extract_version.outputs.major_version }}.0.${{ github.run_number }}
          file: src/PodScrub.Api/Dockerfile-FFmpeg
