name: GitHub Actions Checks

on:
  push:
    paths:
      - '.github/**'

jobs:
  gha-checks:
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    uses: mu88/common/.github/workflows/gha-checks.yml@430f363731065aa9a2be157bc792c1c2b2a97de9 # main
